### PR TITLE
feat: add support for x64

### LINKED ISSUE #22: Add support for wine64
In https://github.com/electron-userland/electron-packager/issues/519 someone asked to be able to use wine64 to run `rcedit.exe`. My suggestion is to use `process.env.WINE || 'wine'` and add a `WINE=wine64` env to the Travis build matrix.

### PR DESCRIPTION
**Pull request by andreineculau**
fixes #22 

PS: I have ignored `.circleci/config.yml` but maybe that should be updated as well, to test both architectures if possible

### CODE REVIEW

**Comment by AndreiSoroka** [comment]
@cap10morgan when we get merge?)

**Comment by malept** [comment]
As it stands, this won't work on macOS Catalina since it requires `wine64`. Also CI should be updated as mentioned in the summary.

**Comment by maximilianschmidt** [comment]
following the fix mentioned in this issue it works for me on catalina: https://github.com/electron/node-rcedit/issues/51#issuecomment-546234084

**Comment by cap10morgan** [comment]
@malept `wine64` works just fine on Catalina and is installed alongside `wine` (which doesn’t work, of course) by `brew install wine`.

**Comment by cap10morgan** [comment]
@AndreiSoroka It’s not up to me. :)

**Comment by malept** [comment]
@cap10morgan my point is that this module does not currently support `wine64` (see #22).

**Comment by cap10morgan** [comment]
@malept This PR fixes that.

**Comment by malept** [comment]
Hmm for some reason I thought it didn't. In any event, CI needs to get updated.

**Comment by andreineculau** [comment]
The reasons why I didn't (and won't) update `.circleci/config.yml`:
* circleci is not set eup for PRs, so it's not easy to asses the quality of the changes
* afaics the CI will still be green after this PRs, thus it is not a matter of "need" but "nice to have"
* currently the CI tests node-rcedit with wine32,rcedit32 on amd64 architecture (the only one available on circleci), and after this PR the CI will test node-rcedit with wine64,rcedit64 instead. Given that this PR doesn't implement a way to force which wine/rcedit version is used, this means that one would need set up circleci to use a 32-bit docker image (or a 32-bit node would probably work as well). To the point, it is not a trivial change.

**Comment by paul321** [comment]
Any news on this merge? A lot of Electron apps are waiting for this on MacOS Catalina

**Comment by cap10morgan** [comment]
What's the status of getting a new release now that this is merged? Thanks!

**Comment by zcbenz** [comment]
It ought to be released automatically but the CI failed on master... I'll fix it.

**Pull request merged**
